# coding: utf-8

"""
    3D Annotation API with JWT

    A JWT-Protected API for 3D Object Annotation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from openapi_server.apis import router
from fastapi.middleware.cors import CORSMiddleware
# from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="3D Annotation API with JWT",
    description="A JWT-Protected API for 3D Object Annotation",
    version="1.0.0",
)

# 这里要给跨域的加允许信息
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  # List your frontend URL here
    allow_credentials=True,
    allow_methods=["*"],  # Allows all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],  # Allows all headers
)


app.include_router(router)
