# coding: utf-8

"""
    3D Annotation API with JWT

    A JWT-Protected API for 3D Object Annotation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Annotation(BaseModel):
    """
    Annotation
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier for the annotation")
    pcd_file_id: Optional[StrictInt] = Field(default=None, description="The ID of the .pcd file")
    label: StrictStr = Field(description="Label for the annotated object")
    geometry: StrictStr = Field(description="The shape of the bounding box")
    size: Optional[Dict[str, Any]] = None
    position: Optional[Dict[str, Any]] = None
    rotation: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "pcd_file_id", "label", "geometry", "size", "position", "rotation"]

    @field_validator('geometry')
    def geometry_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('sphere', 'cube', 'polygon',):
            raise ValueError("must be one of enum values ('sphere', 'cube', 'polygon')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Annotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Annotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "pcd_file_id": obj.get("pcd_file_id"),
            "label": obj.get("label"),
            "geometry": obj.get("geometry"),
            "size": obj.get("size"),
            "position": obj.get("position"),
            "rotation": obj.get("rotation")
        })
        return _obj


